# Generated by Django 3.0.4 on 2022-06-12 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='栽培エリア')),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='野菜')),
                ('icon', models.CharField(blank=True, default='<i class="fa-solid fa-seedling"></i>', max_length=255, null=True, verbose_name='Icon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrowingCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(blank=True, max_length=255, null=True, verbose_name='品種')),
                ('seeding_date', models.DateField(blank=True, null=True, verbose_name='種まき日')),
                ('planting_date', models.DateField(blank=True, null=True, verbose_name='植付日')),
                ('transplanting_date', models.DateField(blank=True, null=True, verbose_name='移植日')),
                ('harvest_date_start', models.DateField(blank=True, null=True, verbose_name='収穫開始日')),
                ('harvest_date_end', models.DateField(blank=True, null=True, verbose_name='収穫完了日')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetablegarden.Area', verbose_name='栽培エリア')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('vegetable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetablegarden.Vegetable', verbose_name='野菜')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='畑')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CropManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='項目')),
                ('text', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vegetablegarden/', verbose_name='画像')),
                ('date', models.DateField(blank=True, null=True, verbose_name='実施日')),
                ('growing_crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vegetablegarden.GrowingCrop', verbose_name='作物')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vegetablegarden.Field', verbose_name='畑'),
        ),
        migrations.AddField(
            model_name='area',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
